name: Weekly Update README

on:
  # Run every Sunday at 00:00 UTC
  schedule:
    - cron: "0 0 * * 0"
  # Allows you to run this workflow manually from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update date in README
        run: |
          # Install Python if needed; ubuntu-latest typically has it already
          python3 update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Automated monthly/year update in README [skip ci]" || echo "No changes to commit"
          git push
